import { useMemo } from "react";

export const Component = () => {
  const autoGeneratedIds = useMemo((): string[] => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);
};

function App() {
  return <div></div>;
}

export default App;
